### ISSUE TITLE
Improve bundle size

### ISSUE THREAD

**Issue by TheHolyWaffle** [Grsmto/simplebar#391] opened 2019-10-21 14:43 UTC
simplebar is lovely, but it's big. Incredibly big! https://bundlephobia.com/result?p=simplebar@5.0.2

I'd like to request to shave some unnecessary bloat from this package if possible:
- core-js is not needed in normal circumstances
- resize-observer-polyfill should not be included by default, it's up to the end developer to include polyfills where needed

**Comment by Grsmto** [comment] 2019-10-21 15:05
Hi,
Thanks for your report,

Unfortunately I believe the unecessary bloat you are mentionning is not:

- core-js is needed because we support certain browsers by default and babel-preset-env is defining what ES features need to be polyfilled thanks to core-js based on our browserlist config
- resize-observer-polyfill is included because the whole point of SimpleBar is to provide a solution for crossbrowser support, so if it doesn't support at least every modern browsers, it has absolutely no purpose and you could just customise scrollbars with CSS directly (on Chrome & Firefox).

However I agree that we could not include it in the bundle and just have it as an optional dependency (`npm install simplebar resize-observer-polyfill`). But I'm worried people skip it and report issues for things to not work as intended.

Also I might close this as it's a duplicate of  #372

**Comment by Grsmto** [comment] 2019-10-21 15:11
The UMD bundle is huge, I'm not sure why. That's what bundlephobia is parsing I suppose.
However the ESM one should be much smaller and if you use Webpack or a module bundler (hopefully most of the people using this lib), it should fine.

**Comment by TheHolyWaffle** [comment] 2019-10-21 15:22
@Grsmto Bundlephobie is actually correct here. The simplebar.esm.js bundle is already at 34kb, and that doesn't include the core-js imports yet. In total it adds up to being 60kb uncompressed. 

For my end users, I'd like to only target modern browsers. So core-js inherently duplicates the size. 

As for the resizer polyfill, I don't think we should treat developers as donkeys :) With some proper explanation on readme they will know about this caveat.

**Comment by Grsmto** [comment] 2019-10-21 15:30
>I don't think we should treat developers as donkeys :)

It's not about treating people as donkeys but as it's not currently working this way, people might upgrade to the latest version without necesarily reading the README again...It's a tricky one.

**Comment by TheHolyWaffle** [comment] 2019-10-21 15:38
For sure, such a change would be breaking and and thus results in an increment of the MAJOR version of the package.

**Comment by unindented** [comment] 2019-10-23 23:24
I agree. Letting users polyfill whatever they need, and removing `resize-observer-polyfill` from `simplebar` in a major release, would be the right call here.

**Comment by bjufre** [comment] 2021-06-17 13:12
Is there any news about this? Using 2.3.3 and it's still pulling in the `core-js` deps

**Comment by ambichetan** [comment] 2022-06-21 22:24
Hello @Grsmto any update on this?

**Comment by Daniel-Knights** [comment] 2022-10-06 09:09
I think the README needs to be updated. 6kb looks like the unbundled size of the main JS file, bundled, the ES file is 26kb gzipped

**Comment by Grsmto** [comment] 2022-10-06 09:55
Yeah the README is really out of date about this. This issue is major and I worked on solving it in v6 but never had time to actually release it.
It would be great to release v6 but I need some time to work on it. In the meanwhile I will update the README.

**Closed** 2023-01-15 21:13 UTC
