### ISSUE TITLE
Only one child

### ISSUE THREAD

**Issue by masta-lama** [Grsmto/simplebar#201] opened 2018-08-30 08:52 UTC
Why the current script accept only one child
You just have to move all children on contentEl of you'r class ?
I quick read but line 2569 `while (this.el.firstChild) {` seem the cause.
I try to iterate on `this.el.children` but `this.el` already get only one element ?

**Comment by Grsmto** [comment] 2018-08-30 12:07
Sorry I don't understand your issue. What are you trying to do?

**Comment by masta-lama** [comment] 2018-08-30 12:15
&lt;div data-simplebar&gt;
&lt;div&gt;1&lt;/div&gt;
&lt;div&gt;2&lt;/div&gt;
&lt;/div&gt;
Only div with 1 are put into div.simplebar-content

The div with 2 aren't move into div.simplebar-content
So i get the scroll only on div 1.

**Comment by Grsmto** [comment] 2018-11-06 22:41
I'm not able to reproduce this issue.
Please try again with latest version and maybe provide a jsfiddle.
I'm closing for now!

**Closed by Grsmto** 2018-11-06 22:41 UTC
