### ISSUE TITLE
Exception raised.

### ISSUE THREAD

**Issue by SMTStuck** [Grsmto/simplebar#496] opened 2020-07-17 23:26 UTC
I'm getting the following exception:

```
Exception: TypeError: can't convert null to object
Line: 666
FunctionName: sloppyArrayMethod
```

Within a rather empty HTML page:

```
<html>
	<head>
		<title>Test</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" href="https://unpkg.com/simplebar@latest/dist/simplebar.css"/>
		<script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>
	</head>
	<body>
	</body>
</html>
```

This issue did not appear inn version 3.1.5.

**Comment by Grsmto** [comment] 2020-07-30 00:30
Please follow the issues template cause this doesn't really help. We need to know at least in what environment this is happening (what browser version etc.).

**Comment by SMTStuck** [comment] 2020-07-30 05:11
Firefox 78.0.2

You could have tested the html code in less time it took you to write that comment. Nevertheless...

1) Make a new .html file with the given HTML code
2) Save it where you fancy.
3) Open it, view the console and refresh to see the error.

I raised the issue 12 days ago and have found a suitable alternative in the meantime, so I won't be giving more than this.

All the best.

**Comment by Grsmto** [comment] 2020-07-30 11:44
> You could have tested the html code in less time it took you to write that comment. Nevertheless...

I guess it's good that I asked because I can't reproduce this issue. So I could have spend hours trying on every possible browsers without being able to even have this issue ;)

Anyway, I tried your reproduction steps and couldn't get the issue on this exact Firefox version, so I'm closing this.

Thanks.

**Closed by Grsmto** 2020-07-30 11:44 UTC
