### ISSUE TITLE
How to fix this bug of dropdown-menu, using Simplebar?

### ISSUE THREAD

**Issue by gusbemacbe** [Grsmto/simplebar#96] opened 2017-07-07 18:03 UTC
I use Bootstrap 4. I builded language picker/selector/switcher's dropdown in the right of the navbar. When I added data-simplebar tag for the tag `ul`, it always fixed/open the dropdown/toggle. See the small screenshot:

![screen shot 2017-07-07 at 14 56 04](https://user-images.githubusercontent.com/2257024/27970397-07399888-6325-11e7-887d-d230c2f3e411.png)

Language Selector HTML:

```
<div  class="btn-group dropdown pull-right">
        <li class="dropdown language-selector list-inline">
    
            <a href="index.php" class="dropdown-toggle estilo" data-toggle="dropdown" data-close-others="true">
                Idioma
            </a>
    
            <ul data-simplebar class="dropdown-menu pull-right scrollable-menu" role="menu">
                <li>
                    <a href="?lang=catalan" name="catalan" class="estilo">
                        <img src="imagens/cat.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=german" name="german" class="estilo">
                        <img src="imagens/de.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=english" name="english" class="estilo">
                        <img src="imagens/en.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=spanish" name="spanish" class="estilo">
                        <img src="imagens/es.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=french" name="french" class="estilo">
                        <img src="imagens/fr.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=italian" name="italian" class="estilo">
                        <img src="imagens/it.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=dutch" name="dutch" class="estilo">
                        <img src="imagens/nl.svg">
                    </a>
                </li>
                <li>
                    <a href="index.php" class="estilo">
                        <img src="imagens/pt-br.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=romanian" name="romanian" class="estilo">
                        <img src="imagens/ro.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=georgian" name="georgian" class="estilo">
                        <img src="imagens/ka.svg">
                    </a>
                </li>
                <li>
                    <a href="?lang=greek" name="greek" class="estilo">
                        <img src="imagens/el.svg">
                    </a>
                </li>
            </ul>
    
        </li>
    </div>
```

Language Selector CSS:

```
.dropdown-menu>.active>a, .dropdown-menu>.active>a:focus, .dropdown-menu>.active>a:hover {
    background-color: #FBC6C6;
    background-image: none;
}

.btn-group {
    background-color: transparent;
    border-top-left-radius: 5px;
}

.btn-group:hover {
    border-top-left-radius: 0px;
}

.dropdown-menu {
    min-width: 100%;
}

.language-selector .dropdown-menu {
    -moz-background-clip: padding;
    -moz-border-radius: 3px 3px 3px 3px;
    -webkit-background-clip: padding-box;
    -webkit-border-radius: 3px 3px 3px 3px;
    background: var(--preto-meio-transparente);
    background-clip: padding-box;
    border: none;
    border-bottom-left-radius: 0px;
    border-bottom-right-radius: 0px;
    border-top-left-radius: 10px;
    margin: 0;
    /*overflow: none;*/
    padding: 0;
    width: auto;
}

.language-selector .dropdown-menu>li {
    border-bottom: none;
}

.language-selector .dropdown-menu>li a {
    -moz-background-clip: padding;
    -moz-border-radius: 0;
    -moz-transition: all 300ms ease-in-out;
    -o-transition: all 300ms ease-in-out;
    -webkit-background-clip: padding-box;
    -webkit-border-radius: 0;
    -webkit-transition: all 300ms ease-in-out;
    background-clip: padding-box;
    border-radius: 0;
    color: black;
    display: block;
    font-weight: lighter;
    margin: 0;
    padding-bottom: 5px;
    padding-left: 5px;
    padding-right: 0px;
    padding-top: 5px;
    transition: all 300ms ease-in-out;
}

.language-selector .dropdown-menu>li a img {
    margin-right: 5px;
    vertical-align: middle
}

.language-selector .dropdown-menu.pull-right {
    -moz-background-clip: padding;
    -moz-border-radius: 3px 0 3px 3px;
    -webkit-background-clip: padding-box;
    -webkit-border-radius: 3px 0 3px 3px;
    background-clip: padding-box;
    border-radius: 3px 0 3px 3px;
    margin-right: 5px;
}

.language-selector {
    margin-top: 0;
}

.language-selector>.dropdown-toggle {
    -moz-background-clip: padding;
    -moz-border-radius: 3px;
    -webkit-background-clip: padding-box;
    -webkit-border-radius: 3px;
    background-clip: padding-box;
    border-radius: 3px;
    display: inline-block;
    padding: 10px 0px;
}

.links-list {
    padding-bottom: 8px;
    padding-top: 14px;
    white-space: nowrap;
}

.list-inline {
    color: var(--ouro-elegante);
    font-weight: normal;
    list-style: none;
    padding-left: 5px;
}

.list-inline>li {
    display: inline-block;
    padding-left: 5px;
    padding-right: 5px;
}

.list-inline>li:first-child {
    padding-left: 0;
}

#menu-0 {
    position: absolute;
    z-index: 999;
}

.scrollable-menu {
    height: auto;
    max-height: 100px;
    overflow-x: hidden;
}

a.estilo {
    color: var(--ouro-elegante);
    text-decoration: none;
}

ul.estilo, ol.estilo {
    margin-bottom: 8.5px;
    margin-top: 0;
}
```

**Comment by Grsmto** [comment] 2017-09-29 13:44
Closing as this is a duplicate of #107 . Thank you for the report!

**Closed by Grsmto** 2017-09-29 13:44 UTC
