### ISSUE TITLE
Can't bind scroll event on a horizontal scrollbar

### ISSUE THREAD

**Issue by WebKieth** [Grsmto/simplebar#149] opened 2018-02-27 13:30 UTC
I want to subscribe on horizontal scroll one of table wrappers, but my callback dont work.
I have got multiple tables with horizontal scrollbar. All of them I put into the window, like an array of objects:

``` coffeescript
tableScroller = {
  moduleName: '.table'
  barsArray: []
  init: (options) ->
    module = $(this.moduleName)
    if options 
      if options.maxHeight
        module.wrap("
          <div class='simplebar' style='max-height: #{options.maxHeight}px'>
        </div>")
    else
      module.wrap("
        <div class='simplebar'>
        </div>")
    thisBar = module.parents(".simplebar")
    thisBar.each (i) ->
      that = $(this)
      that.attr("id":"simplebar--#{i}")
      bar = new Simplebar(document.getElementById("simplebar--#{i}"), {autoHide: false})
      barsArray = tableScroller.barsArray
      barsArray.push bar
      window.xScrollbars = barsArray
```

Into my table of data I want to stick header and syncronise it with horizontal scrollbar:
```coffeescript
init: (options) ->
  selector = options.selector
  header = $(selector)
  if options
    if options.scroll == 'simplebar'
      scrollNode = $(window.bodyScroller.getScrollElement())
    else
      scrollNode = $("body")

  headerHeight = $('.header').height()
  lastScrollPoint = false
  scrollNode.scroll (e) ->
    #This callback works properly
    hOffTop = header.offset().top - headerHeight
    if hOffTop <= 0
      lastScrollPoint = header.parents("div:first").offset().top - headerHeight
      #stick header above table
      stickHead.fix(header, {
        offset: headerHeight,
        event: e
        })
    if lastScrollPoint > 0
      #unstick header - works nice too
      stickHead.stick(header)

  if window.xScrollbars
    xScrollbars = window.xScrollbars
    xScrollbars.forEach (scrollbar, index) ->
      #check all scrollbars and find which i need
      el = scrollbar.getScrollElement()
      posibleFixedHeader = $(el).find(selector)

      if posibleFixedHeader.length > 0
        #here I found el - it's a needed node with class 'simplebar-scroll-content'
        el.addEventListener 'scroll', (e) ->
          #that code dont work with and without preventing
          e.preventDefault()
          console.log('scroll')
```
And mousewheell dont scroll horizontal scrollbar into its area.

**Comment by Grsmto** [comment] 2018-03-02 02:09
Hi @WebKieth , this seems like a duplicate of #111.
I'm not sure this is a SimpleBar problem. Does this happen only when you use SimpleBar?

**Closed** 2018-03-12 02:31 UTC
