### ISSUE TITLE
drag scroll button

### ISSUE THREAD

**Issue by mderakhshi** [Grsmto/simplebar#659] opened 2023-03-09 19:12 UTC
I use core document and install simplebar with jquery
Mouse scroll works well
But when we drag the scroll button
It does the opposite
If we hold the button and move down, it moves up and vice versa
image of problem: https://pasteboard.co/ct90st4ZWJm2.png { Dragging the scroll button with the mouse moved it up, but the scroll button and content moved down }

**Comment by exilvm** [comment] 2023-03-30 03:18
Hello!

When reporting an issue, it's important to provide a reproducible demo along with its source code so that we can properly debug it. including just an image is kind of pointless as it does not show us the problem. 

@Grsmto I think you should close this issue unless more information is provided.

**Comment by yosefebrahimi7** [comment] 2023-04-11 02:24
I have same issue in nextjs-version13 and tailwind-css!

```
"use client";

import dynamic from "next/dynamic";

import "./assets/globals.css";
import "./assets/fonts/dana.css";

const SimpleBarReact = dynamic(
  () => import("simplebar-react").then((C) => C),
  {
    ssr: false,
  }
);

function RootLayout(props) {
  const { children } = props;

  return (
    <html lang="fa">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.js. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body dir="rtl" className="overflow-hidden h-screen">
        <SimpleBarReact
          data-simplebar-direction="rtl"
          className="max-w-full h-full overflow-x-hidden"
          autoHide={true}
        >
          {children}
        </SimpleBarReact>
      </body>
    </html>
  );
}

export default RootLayout;
```

**Comment by GSilidis** [comment] 2023-04-12 10:08
Have the same problem on 6.2.4 version. Here's pen with some example code, where this bug is reproducible (try to drag vertical scroll handle, horizontal - works OK): https://codepen.io/GSilidis/pen/RweWyNE. Reproduced on Chrome 111 and Firefox ESR 102.9

**Closed** 2023-04-15 16:29 UTC

**Comment by yosefebrahimi7** [comment] 2023-04-18 18:20
The problem was solved for me too.
**thanks a lot**
