### ISSUE TITLE
Native Scrollbar Shown When Zoomed In

### ISSUE THREAD

**Issue by audinue** [Grsmto/simplebar#11] opened 2015-08-04 08:47 UTC
When you zoom in the native scrollbar shown.

**Comment by Grsmto** [comment] 2015-08-14 15:57
In which browser? I can't reproduce this issue.

**Comment by audinue** [comment] 2015-08-15 10:33
Sorry, it is zoomed out not zoomed in.

Here is the screenshots:
Before:
![before](https://cloud.githubusercontent.com/assets/1407800/9288499/9be81f78-4373-11e5-9536-e387ace3157f.png)

After Zoomed Out:
![after](https://cloud.githubusercontent.com/assets/1407800/9288500/9be8c270-4373-11e5-8d23-4cc0fe2ec2bc.png)

**Comment by bobbiejwilson** [comment] 2016-12-28 00:24
I'm getting this on FF without being "zoomed in". Default view.

**Comment by Grsmto** [comment] 2016-12-28 13:19
@bobbiejwilson what version of FF/platform/Simplebar?
Thanks

**Comment by bobbiejwilson** [comment] 2016-12-28 19:01
FF/Win10/Simplebar2

I was using min-width, works fine in chrome, not in FF. Switched to width and it seems to work on every other refresh.

**Comment by byman64** [comment] 2017-07-31 21:37
same here, 
Chrome show 1 or 2 pixel of the original scrollbar. Zoom In/Out disapper or appear more
Edge works fine
http://www.quakearea.com/q3statusbot/gameq/index_simplebar.php
I will keep that link for a while and than I will remove.
Let me know 
thx

**Comment by jamesrpublications** [comment] 2017-10-13 04:24
Does anyone know how to fix this?

**Comment by batsuuri** [comment] 2018-04-06 10:24
Only FF shows native scrollbar and simplebar shows both.
![image](https://user-images.githubusercontent.com/1828078/38416585-bf35129a-39c7-11e8-8c5b-1c8ebc5b3600.png)

**Comment by batsuuri** [comment] 2018-04-06 10:32
Figured it out reading from https://github.com/Grsmto/simplebar/issues/142. It caused set custom class that div controlled by simplebar.

**Comment by MattCz** [comment] 2018-04-06 13:51
I think that the padding/margin should be recalculated inside of window "resize" event. It is because the native scrollbar in FF (not sure about other browsers) changes it's width. So padding set by scrollbar element becomes not actual. The best would be to use fixed percentage padding and percentage width. Hope that helps.

**Comment by Grsmto** [comment] 2018-04-11 16:06
@MattCz the problem is that the browser zoom is doing a "out of browser context" zoom. Which means that the app code can't have any clue of the current zoom and the actual impact on the layout. 
It does trigger a `resize` event but the calculation here will output exactly the same values as before you zoomed in/out. So the problem happens.

I think only solution is to hack around `window.devicePixelRatio` and browser specific code.
The core idea of this plugin is around a hack anyway so it may be possible. 
This issue is now my highest priority as this is really breaking and it might not be worth keep working on the plugin if we don't find a solution for such a major issue!

**Comment by KingSora** [comment] 2018-05-08 08:07
@Grsmto Since I've developed my own scrollbar plugin, I've faced the same issue. Indeed this issue isn't simple to fix and it required me a lot of research and experiments to fix it, but in the end I've found a solution.

Let me explain how I fixed it and what my approach was:

- What causes this bug? - This bug is caused because the browser won't change the size of the scrollbars if you zoom. Lets take a example you have zoomed to `1` (100%), in this mode your page has a pixel ratio of 1:1. If you measure now the scrollbar size (which is necessary to make your plugin work) this size is correct for this zoom. Lets assume the scrollbars have a size of `17px`. Now you zoom out to `0.5` (50%), the browser is changing the pixels of your webpage to this zoom (so a div which had 200px height appears now as it would have 100px height). But altough everything is now half as big as it was, visually the scrollbar still takes the same amount of space as it took as the zoom was at `1` (100%). So the visual size of the scrollbar is always absolute. Lets measure the "logic" size of the scrollbar again now with this zoom of `0.5` (50%). The size which now is computed should be something around `34px`, because everything is half as big visually, but the scrollbar isn't.

- How can I fix this bug? - Now that we know how this bug is exactly caused and all its characteristics, we are able to write a fix for it. The hardest part is to detect the zoom event. As you mentioned the zoom can be catched with the `resize` event, but inside you should do some customizations because a `resize` event is also fired after resizing the window. In this customized resize event you have to tell your plugin instances to update their value of the scrollbar size. This would be the whole fix.

The bug is also caused only in browsers in which the scrollbarsize is visually absolute, such as firefox. The internet explorer for example scales its scrollbars with the zoom, so this bug isn't present there.

If you need more help, you can take a look at the code of my scrollbar plugin [here](https://github.com/KingSora/OverlayScrollbars/blob/master/js/OverlayScrollbars.js#L1644), or you can ask me directly. 

I hope I could help you a bit!

**Comment by Grsmto** [comment] 2018-05-08 14:50
I don't know if browser behaviour changed but I remember trying to fix this in 2015 when this issue was raised and figured out it was impossible due to the fact that there was no way to measure the scrollbar width properly after zoom in/out on Chrome.

But I recently took a look again and now it works just fine! I have implemented a solution already on the `next` branch and I'm preparing a new release of the plugin for very soon.

Thanks @KingSora for your input, I checked your plugin already and I was impressed by the amount of work that has been done there! Especially the demo website, good job!

**Comment by yaymukund** [comment] 2018-05-09 14:48
@Grsmto That's great news! From testing the branch, it seems to fix this exact issue on my end.

Do you have an ETA for the new release? Excited to use it in production 😄

**Comment by Grsmto** [comment] 2018-05-09 14:54
@yaymukund yes I'm actively working on it and I hope to have a beta in a couple of days.
Thanks for the feedback! Right now I'm working on automated tests to make sure it's stable and can be used safely in production for current users.

**Comment by Grsmto** [comment] 2018-07-14 19:49
Closed in simplebar@3.0.0-beta.0.

**Closed by Grsmto** 2018-07-14 19:49 UTC
Labels: Help needed, bug
