### ISSUE TITLE
SimpleBar together with Framework7

### ISSUE THREAD

**Issue by AntonKremer** [Grsmto/simplebar#527] opened 2020-10-04 05:49 UTC
Actually simple bar is exactly want I was looking for, but

I am using simpleBar together with framework7. After some page changes simplebar is not working any longer. All the simplebar warappers are still available, recalculate does not help.

Example
Sandbox: https://codesandbox.io/s/floral-https-t9nuf?file=/app.js
Fullscreen: https://t9nuf.csb.app/

(1) click on "Info"
(2) page incl scroll bar is generated; everything is working
(3) go back
(4) click on "info" again

-> Scrolling is possible, but no scrollbar is shown any more...

Any thoughts? It seems that the listeners are lost...

**Comment by Grsmto** [comment] 2020-10-06 15:52
Hey, thanks for the reproductible example, that's interesting!
It seems like this framework is caching the page content for reuse. I guess you noticed that since you put a `new Date()` and we can see the time is always the same so the page content is never re-rendered.
The problem here is that SimpleBar is unmounting automatically when it's being removed from the DOM (when you press "back"), but when it's called again, SimpleBar thinks it's already mounted because the DOM is already set with `data-simplebar="init"` on it, so it doesn't mount again. Which makes it not work!

However this problem has been solved in the latest beta version! But after testing I just realised there is another issue with the browser version of SimpleBar, which hopefully should be solved soon, so please keep an eye on this.

**Comment by AntonKremer** [comment] 2020-10-06 16:31
Hi Adrien,

many thanks for looking at this topic. I noticed as well that it seems that all the bindings are lost and the events (like touch) are not longer received (all the wrappers remain)

Would be great if this is solved with the next version...

Many thanks & best regards
Andreas

**Comment by AntonKremer** [comment] 2020-10-08 06:50
Hi Adrien,

do you have a rough idea when the next version (solving this issue) will be available?

Many thanks & best regards
Anton

**Comment by Grsmto** [comment] 2023-01-19 20:11
Closing as hopefully this is fixed by now!

**Closed by Grsmto** 2023-01-19 20:11 UTC
