### ISSUE TITLE
Is it possible to set max-width for scrollbar?

### ISSUE THREAD

**Issue by RemoHz** [Grsmto/simplebar#155] opened 2018-03-23 05:54 UTC
Everything works fine. Really good plugin!
Just wondering that is there a way to set max width for scroll bar? 
Currently not quite sure how does the script to calculate the scroll bar width.

**Comment by Grsmto** [comment] 2018-03-23 10:49
Duplicate of #125

**Closed** 2018-03-31 01:15 UTC
